name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: trashuser
          POSTGRES_PASSWORD: trashpass
          POSTGRES_DB: trashdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1 libglib2.0-0 libsm6 libxrender1 libxext6
        sudo apt-get install -y postgresql-client

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install torch==2.0.1+cpu torchvision==0.15.2+cpu -f https://download.pytorch.org/whl/torch_stable.html

    - name: Setup environment variables
      run: |
        echo "DATABASE_URL=postgres://trashuser:trashuser@localhost:5432/trashdb" >> $GITHUB_ENV
        echo "MEDIA_ROOT=media" >> $GITHUB_ENV
        echo "SECRET_KEY=trash-secret-key" >> $GITHUB_ENV

    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: |
        python manage.py test
      env:
        DATABASE_URL: ${{ env.DATABASE_URL }}
        MEDIA_ROOT: ${{ env.MEDIA_ROOT }}
        SECRET_KEY: ${{ env.SECRET_KEY }}
